env: dev
replicaCount: 2

image:
  tag: 0191cb18367e786dab73ab3afc74d7cfa6a7acc0

ingress:
  enabled: true
  auth:
    enabled: false
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: devlunart.loop.onl
      paths:
      - /
  tls:
    - secretName: devlunart-loop-onl
      hosts:
      - devlunart.loop.onl

autoscaling:
  minReplicas: 2
  maxReplicas: 5
